apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: myaiplatform
  name: myaiplatform-pvc
  namespace: myaiplatform
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi